spring:
  application:
    name: microservice-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:4200"
              - "https://backendfinal-ddc44.web.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: microservice-sales
          uri: lb://microservice-sales
          predicates:
            - Path=/api/v1/ventas/**
        - id: microservice-product
          uri: lb://microservice-product
          predicates:
            - Path=/api/v1/videojuegos/**



        - id: microservice-users-api
          uri: lb://microservice-users
          predicates:
            - Path=/api/v1/user/**

        - id: microservice-users-swagger
          uri: lb://microservice-users
          predicates:
            - Path=/microservice-users/swagger-ui.html
            - Path=/microservice-users/swagger-ui/**
          filters:
            - RewritePath=/microservice-users/(?<segment>.*), /${segment}


        - id: microservice-security
          uri: lb://microservice-security
          predicates:
            - Path=/api/v1/auth/**
        - id: microservice-client
          uri: lb://microservice-client
          predicates:
            - Path=/api/v1/client/**
